name: uninet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  dotted_border: ^2.0.0+3
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.2.0
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.3.2
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.7
  get_it: ^7.6.7
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.1
  image_picker: ^1.1.1
  pinput: ^3.0.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: null
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
  # To add assets to your application, add an assets section, like this:
flutter_native_splash:
  color: "#4169E1"
  image: assets/images/logo2.png
  color_dark: "#4169E1"
  image_dark: assets/images/logo2.png

  android_12:
    image: assets/images/logo2.png
    icon_background_color: "#4169E1"
    image_dark: assets/images/logo2.png
    icon_background_color_dark: "#121212"

  web: false
