// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBowSzVTba7cEO4w_4q5fkq_FjRL2CYmDU',
    appId: '1:386040793012:web:f86e6b525ccd53f41b94e1',
    messagingSenderId: '386040793012',
    projectId: 'uninet-32c4a',
    authDomain: 'uninet-32c4a.firebaseapp.com',
    storageBucket: 'uninet-32c4a.appspot.com',
    measurementId: 'G-CC9XK3KT1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9MdWH2htGy8asTWj_up6MtAF7skuSpUM',
    appId: '1:386040793012:android:69b5c63128da5ab71b94e1',
    messagingSenderId: '386040793012',
    projectId: 'uninet-32c4a',
    storageBucket: 'uninet-32c4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp4jLl8iTO-qR3ZSn9WRea3tleRTL95Hs',
    appId: '1:386040793012:ios:c2c3da81e8900a8e1b94e1',
    messagingSenderId: '386040793012',
    projectId: 'uninet-32c4a',
    storageBucket: 'uninet-32c4a.appspot.com',
    iosClientId: '386040793012-h3gmv8qast5vf1cs0tt6eds8dgkd7ltm.apps.googleusercontent.com',
    iosBundleId: 'com.example.uninet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp4jLl8iTO-qR3ZSn9WRea3tleRTL95Hs',
    appId: '1:386040793012:ios:b8f919810b760b131b94e1',
    messagingSenderId: '386040793012',
    projectId: 'uninet-32c4a',
    storageBucket: 'uninet-32c4a.appspot.com',
    iosClientId: '386040793012-jp1oqjhokr52or75m0d6noojmtbieu60.apps.googleusercontent.com',
    iosBundleId: 'com.example.uninet.RunnerTests',
  );
}
